CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY, -- Matches Clerk User ID
  email TEXT UNIQUE NOT NULL,
  role TEXT DEFAULT 'member', -- 'admin' or 'member'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  access_level TEXT DEFAULT 'public', -- 'public' or 'admin'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Initial Categories Seed
INSERT INTO categories (name, slug, access_level)
VALUES 
  ('General', 'general', 'public'),
  ('Admin Stuff', 'admin-stuff', 'admin')
ON CONFLICT (slug) DO NOTHING;

CREATE TABLE IF NOT EXISTS CALENDARS (
  CALENDAR_ID SERIAL PRIMARY KEY,
  CALENDAR_MEMBER INTEGER NOT NULL DEFAULT 0,
  CALENDAR_NAME VARCHAR(50) NOT NULL,
  CALENDAR_SUBNAME VARCHAR(50),
  CALENDAR_DATE DATE NOT NULL,
  CALENDAR_DATE_END DATE,
  CALENDAR_EVENT TEXT NOT NULL,
  PLACE_ID INTEGER,
  CATEGORY_ID INTEGER,
  CALENDAR_NUM NUMERIC(9,3),
  CALENDAR_NUM2 NUMERIC(9,3)
);

COMMENT ON COLUMN CALENDARS.CATEGORY_ID IS 'Links depending on Cal Name';

CREATE TABLE IF NOT EXISTS FAMILY_MEMBERS (
  FAMILY_MEMBER_ID SERIAL PRIMARY KEY,
  FAMILY_FIRST_NAME VARCHAR(50) NOT NULL,
  FAMILY_MIDDLE_NAME VARCHAR(50),
  FAMILY_LAST_NAME VARCHAR(50),
  FAMILY_MAIDEN_NAME VARCHAR(50),
  FAMILY_NICKNAME VARCHAR(100),
  FAMILY_SEX VARCHAR(1) NOT NULL,
  FAMILY_BIRTHDAY DATE,
  FAMILY_DEATHDAY DATE,
  FAMILY_DESC TEXT,
  FAMILY_EMAIL VARCHAR(100),
  FAMILY_PHONE VARCHAR(50),
  FAMILY_WEBSITE VARCHAR(255),
  CLERK_USER_ID VARCHAR(255) UNIQUE,
  FAMILY_IMAGE_URL VARCHAR(512)
);

CREATE TABLE IF NOT EXISTS PLACES (
  PLACE_ID SERIAL PRIMARY KEY,
  PLACE_OWNERSHIP_ID INTEGER NOT NULL DEFAULT 0,
  CHAIN_ID INTEGER NOT NULL DEFAULT 0,
  PLACE_NAME VARCHAR(100) NOT NULL,
  PLACE_NAME_2 VARCHAR(100),
  PLACE_DESC TEXT,
  ARCH_ID INTEGER,
  PLACE_ADDR VARCHAR(100),
  PLACE_ADDR_2 VARCHAR(100),
  PLACE_CITY VARCHAR(50),
  PLACE_STATE VARCHAR(2),
  PLACE_ZIP VARCHAR(10),
  PLACE_COUNTRY VARCHAR(5) NOT NULL,
  PLACE_PHONE VARCHAR(15),
  PLACE_WEBPAGE TEXT,
  PLACE_EMAIL VARCHAR(50),
  PLACE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PLACE_OPEN_DATE DATE,
  PLACE_CLOSE_DATE DATE,
  PLACE_CAPACITY INTEGER
);

CREATE TABLE IF NOT EXISTS ARCHITECTURE (
  ARCH_ID SERIAL PRIMARY KEY,
  ARCH_NAME VARCHAR(100) NOT NULL,
  ARCH_DESC TEXT,
  BUILDING_TYPE_ID INTEGER
);

INSERT INTO ARCHITECTURE (ARCH_ID, ARCH_NAME, ARCH_DESC, BUILDING_TYPE_ID) VALUES
(1, 'Barn', NULL, 1),
(2, 'Automobile Repair Shop', NULL, 2),
(3, 'Convention Center', NULL, 2),
(4, 'Multi-Purpose Arena', NULL, 2),
(5, 'Gas Station', NULL, 2),
(6, 'Hotel', NULL, 2),
(7, 'Skyscraper', NULL, 2),
(8, 'Shop', NULL, 2),
(9, 'Market', NULL, 2),
(10, 'Restaurant', NULL, 2),
(11, 'Shopping Mall', NULL, 2),
(12, 'House', NULL, 3),
(13, 'Duplex', NULL, 3),
(14, 'Townhouse', NULL, 3),
(15, 'Apartment Block', NULL, 3),
(16, 'College', NULL, 4),
(17, 'School', NULL, 4),
(18, 'Library', NULL, 4),
(19, 'Museum', NULL, 4),
(20, 'Theater', NULL, 4),
(21, 'Post Office', NULL, 5),
(22, 'Church', NULL, 9),
(23, 'Airport', NULL, 10),
(24, 'Bus Station', NULL, 10),
(25, 'Parking Garage', NULL, 10),
(26, 'Trailer Park', NULL, 3),
(27, 'Amusement Park', NULL, 13),
(28, 'Arcade', NULL, 13),
(29, 'Auditorium', NULL, 13),
(30, 'Bank', NULL, 2),
(31, 'Bar', 'https://en.wikipedia.org/wiki/Bar', 2),
(32, 'Beer Distributor', NULL, 2),
(33, 'Video Game Developer', NULL, 2),
(34, 'Video Game Publisher', NULL, 2),
(35, 'Video Game Dev/Pub', NULL, 2),
(36, 'Supercenter', NULL, 2),
(37, 'Grocery Store', NULL, 2),
(38, 'Movie Theater', NULL, 2),
(39, 'Stadium', NULL, 2),
(40, 'Book Store', NULL, 2),
(41, 'Sports Complex', NULL, 2),
(42, 'Amphitheatre', NULL, 2),
(43, 'Medical', NULL, 2),
(44, 'Tattoo Parlor', NULL, 2),
(45, 'Brewery', NULL, 2),
(46, 'Bicycle Shop', NULL, 2),
(47, 'Religious', NULL, 2),
(48, 'Gambling', NULL, 2),
(49, 'Concert Venue', NULL, 2),
(50, 'Financial', NULL, 2),
(51, 'Video Game Store', NULL, 2),
(52, 'Automotive Sales', NULL, 2),
(53, 'Office Building', NULL, 2),
(54, 'Liquor Store', 'Sells booze', 2),
(55, 'Day Care', NULL, 2),
(56, 'Family Fun', NULL, 2),
(57, 'Hostel', NULL, 2),
(58, 'Park', NULL, 2),
(59, 'Personal Care', NULL, 2),
(60, 'Campground', NULL, 2),
(61, 'Sports Shop', NULL, 2),
(62, 'Appliance Store', NULL, 2),
(63, 'Discount Store', NULL, 2),
(64, 'Driver''s License Center', 'DMV', 2),
(65, 'Trailhead', 'Somewhere you park your car to get on your bike on the trail', 8),
(66, 'Department Store', 'Sells clothes and other home use items. ', 2),
(67, 'Firehall', NULL, 5),
(68, 'Home Improvement Store', NULL, 2),
(69, 'Clothing Store', 'Sells clothes', 2),
(70, 'Misc Shop', 'Sells all kinds of undefined stuff', 2),
(71, 'Toy Store', NULL, 2),
(72, 'Shooting Range', NULL, 2),
(73, 'Service Center', 'Tools and Repair', 2),
(74, 'Electronics Store', NULL, 2),
(75, 'Real Estate', NULL, 2),
(76, 'Country Club', NULL, 2),
(77, 'Hair Salon', NULL, 2),
(78, 'Steel Mill', NULL, 6),
(79, 'Office Supplies', NULL, 2),
(80, 'Bowling Alley', NULL, 2),
(81, 'Furniture Store', NULL, 2),
(82, 'Pharmacy', NULL, 2),
(83, 'Rest Stop', 'Somewhere to pee and get gas and food on long highway trips', 2),
(84, 'Car Wash', NULL, 2),
(85, 'Courthouse', NULL, 5),
(86, 'Zoo', NULL, 2),
(87, 'Winery', 'Where they make wine', 2),
(88, 'Tourist Attraction', NULL, 2),
(89, 'Tunnel', NULL, 11),
(90, 'Shoe Store', 'Like where Al Bundy worked', 2),
(91, 'Government', 'Any Misc Gov office, hall, floor, meeting place, etc', 5),
(92, 'Monument', 'Any misc monument, statue, plaque, etc', 2),
(93, 'Farm', NULL, 1),
(94, 'Gift Shop', NULL, 2),
(95, 'Convenience Store', NULL, 2),
(96, 'HVAC Service', NULL, 2),
(97, 'Electrical Service', NULL, 2),
(98, 'Plumber', NULL, 2),
(99, 'Food Truck', 'Mobile Unit, can be at many locations', 2),
(100, 'Gym', NULL, 2),
(101, 'Bridge', NULL, 0),
(102, 'Video Rental Store', NULL, 2),
(103, 'Corporate Heaquarters', 'Main office', 2),
(104, 'Police Station', NULL, 5),
(105, 'Pet Store', NULL, 2),
(106, 'Beach', NULL, 2),
(107, 'Distillery', 'Where they make booze', 2),
(108, 'Printing Shop', NULL, 2),
(109, 'Cannabis Store', 'Where they sell marijuana and related products', 2),
(110, 'Cannabis Grower', 'Farm / Lab where they grow the marijuana', 2),
(111, 'Train Station', NULL, 2)
ON CONFLICT (ARCH_ID) DO NOTHING;


INSERT INTO FAMILY_MEMBERS (FAMILY_MEMBER_ID, FAMILY_FIRST_NAME, FAMILY_MIDDLE_NAME, FAMILY_LAST_NAME, FAMILY_MAIDEN_NAME, FAMILY_NICKNAME, FAMILY_SEX, FAMILY_BIRTHDAY, FAMILY_DEATHDAY, FAMILY_DESC) VALUES
(2, 'Alejandra', 'Romina', 'Cartwright', 'Garbovetsky', NULL, 'F', '1982-02-16', NULL, NULL),
(3, 'Isaac', 'Michael', 'Cartwright', NULL, 'Boy; Food Bank, Big Poops', 'M', '2003-10-13', NULL, NULL),
(4, 'Matthew', NULL, 'Zupancic', NULL, 'Matt', 'M', '1978-03-22', NULL, NULL),
(5, 'Terrence', 'Kevin', 'Cartwright', NULL, 'Blair', 'M', '1957-11-06', '2015-01-23', NULL),
(6, 'Michael', 'John', 'Cartwright', NULL, NULL, 'M', '1953-01-26', NULL, NULL),
(7, 'Janet', 'Leigh', 'Cartwright', 'Ergan', 'Mugs', 'F', '1953-09-20', NULL, NULL),
(8, 'Autumn', 'Joy', 'Myer', 'Cartwright', 'Babes', 'F', '1978-12-16', NULL, NULL),
(9, 'Pax', 'Oliver', 'Cartwright', NULL, 'Paxipoo; babby; Snotface Shitbutt; Paxo, Paxito, Gordo, Gordito, Poopers, Poops, Lt Squeakers\n', 'M', '2015-03-04', NULL, NULL),
(10, 'Gaines', NULL, 'Myer', NULL, 'Umcle Games', 'M', '1974-12-20', NULL, NULL),
(11, 'Marcelo', 'Adrián', 'Garbovetsky', NULL, NULL, 'M', '1957-11-08', NULL, NULL),
(12, 'Diana', 'Kim', 'Nichols', 'Cartwright', 'Aunt Dee', 'F', '1959-12-14', '2021-07-04', NULL),
(13, 'Steve', NULL, 'Shefcheck', NULL, NULL, 'M', '1975-12-10', NULL, NULL),
(14, 'Laurel', 'Rebecca', 'Cartwright', 'Shreve', 'La', 'F', '1968-05-03', NULL, NULL),
(15, 'Daniel', NULL, 'Weyandt', NULL, 'Danimus', 'M', '1977-05-09', NULL, NULL),
(16, 'Jakob', 'Matthew', 'Zupancic', NULL, NULL, 'M', '2015-12-22', NULL, NULL),
(17, 'Anne', NULL, 'Cartwright', 'Kotarski', NULL, 'F', '1930-05-10', '2002-03-18', NULL),
(18, 'Joel', 'Lawrence ', 'Zupancic', NULL, 'The Blind Owl', 'M', '1974-12-27', NULL, NULL),
(19, 'Lisa', 'Marie', 'Cartwright', 'Inks', NULL, 'F', '1979-04-18', NULL, NULL),
(20, 'Drew', 'Cole', 'Carter', NULL, NULL, 'M', '1976-02-17', NULL, NULL),
(21, 'Anne', NULL, 'Meals', 'Carter', NULL, 'F', '1977-04-28', NULL, NULL),
(22, 'Ryan', NULL, 'Meals', NULL, NULL, 'M', NULL, NULL, NULL),
(23, 'Nathan', NULL, 'Hufford', NULL, 'Nate', 'M', '1974-10-26', NULL, NULL),
(24, 'Melissa', NULL, 'Hufford', 'Latshaw', NULL, 'F', '1973-11-02', NULL, NULL),
(25, 'Carter', 'Ryan', 'Meals', NULL, NULL, 'M', '2013-08-14', NULL, NULL),
(26, 'Hunter', 'Steven', 'Weyandt', NULL, NULL, 'M', '2015-03-23', NULL, NULL),
(27, 'Adelyn', 'Mae', 'Weyandt', NULL, 'Addy', 'F', '2013-05-20', NULL, NULL),
(28, 'Matthew', 'Colt', 'Nichols', NULL, 'Zippy, Zip', 'M', '1983-08-10', NULL, NULL),
(29, 'Chuck', NULL, 'Christner', NULL, NULL, 'M', '1950-03-08', '2021-09-23', NULL),
(30, 'Blaine', 'Vincent', 'Hohman', NULL, 'Jr', 'M', '1978-07-14', NULL, NULL),
(31, 'Tom', NULL, 'Tomalo', NULL, 'Tom Tomato', 'M', NULL, NULL, NULL),
(32, 'Jen', NULL, 'Heckman', NULL, NULL, 'F', NULL, NULL, NULL),
(33, 'Sean', NULL, 'Clawson', NULL, 'Schwan', 'M', NULL, NULL, NULL),
(34, 'Neil', NULL, 'Kownacki', NULL, 'Niel', 'M', '1990-06-07', NULL, NULL),
(35, 'Brady', 'Daniel', 'Cartwright', NULL, NULL, 'M', '1923-07-14', '1987-09-22', NULL),
(36, 'Kevin', 'Raymond', 'Carmichael', NULL, 'Keving', 'M', '9999-10-31', NULL, NULL),
(37, 'Siyu', NULL, 'Zhang', NULL, 'Tom', 'M', '1991-02-24', NULL, NULL),
(38, 'Silvia', 'Graciela', 'Tanel', NULL, NULL, 'F', '1956-02-02', '2018-10-20', 'Ale''s mom. '),
(39, 'Lorena', 'Daniela', 'Garbovetsky', NULL, NULL, 'F', '1983-07-13', NULL, NULL),
(40, 'James', NULL, 'Frey', NULL, 'Jim', 'M', '1980-04-28', NULL, NULL),
(41, 'Jeffery', 'Paul', 'Wasnesky', NULL, 'Cheez, Cheesecake', 'M', '1975-01-31', NULL, NULL),
(42, 'Stefanie', NULL, 'Weyandt', 'Fawcett', 'Stef', 'F', '1981-01-18', NULL, NULL),
(43, 'Angela', NULL, 'Zupancic', 'Sciurba', NULL, 'F', '1980-06-08', NULL, 'Dated Joel started in like 2015.'),
(44, 'Stephanie', NULL, 'Chanowski', 'Kinkella', NULL, 'F', '1977-10-06', NULL, NULL),
(45, 'Sam', NULL, 'Chanowski', NULL, NULL, 'M', NULL, NULL, NULL),
(46, 'Jillian', 'Anne', 'Chanowski', NULL, NULL, 'F', '2010-04-14', NULL, NULL),
(47, 'Allison', 'Leigh', 'Chanowski', NULL, NULL, 'F', '2006-07-09', NULL, NULL),
(48, 'Jennifer', NULL, 'Zupancic', 'Bennett', NULL, 'F', '1978-07-11', NULL, NULL),
(49, 'Daniel', 'Mook', 'Frey', NULL, 'Danny', 'M', '2013-09-03', NULL, NULL),
(50, 'Chloe', '', 'Wasnesky', NULL, '', 'F', '2008-08-20', NULL, NULL),
(51, 'Gerald', NULL, 'Silvasy', NULL, 'G', 'M', '1974-07-13', NULL, NULL),
(52, 'Jed', 'Brady', 'Nichols', NULL, NULL, 'M', '1978-07-25', NULL, NULL),
(53, 'Timothy', 'Michael', 'Moser', NULL, 'Tim', 'M', '1975-07-20', '2002-01-13', NULL),
(54, 'James', NULL, 'Carnathan', NULL, 'Carny', 'M', '1975-01-22', '2007-01-20', NULL),
(55, 'Aiden', 'Roger Wetzel', 'Kinnear', NULL, NULL, 'M', '1999-04-19', NULL, 'Son of La'),
(56, 'Madison', 'Eliza', 'Zupancic', NULL, 'Maddy', 'F', '2006-06-26', NULL, NULL),
(57, 'Qihao', NULL, 'Zhang', NULL, 'Q', 'M', NULL, NULL, 'DBA at MSA'),
(58, 'Beth', NULL, 'Burkovich', NULL, 'Peely', 'F', '1978-01-12', NULL, NULL),
(59, 'Gary', 'Kevin', 'Maginnis', NULL, NULL, 'M', '9999-11-15', NULL, 'bf of Peely'),
(60, 'Michael', NULL, 'Eckert', NULL, NULL, 'M', '1974-09-26', NULL, NULL),
(61, 'Daria', NULL, 'Eckert', NULL, NULL, 'F', '1986-04-20', NULL, NULL),
(62, 'Tatiana', 'Elizabeth', 'Eckert', NULL, '', 'F', '2014-06-10', NULL, NULL),
(63, 'Elaine', NULL, 'Kinkella', NULL, 'Yo', 'F', '1952-09-19', NULL, NULL),
(64, 'Julia', NULL, 'Shefcheck', 'Augustine', 'Julia Ghoulia', 'F', '9999-10-30', NULL, NULL),
(65, 'Magdeline', NULL, 'Shefcheck', NULL, 'Maggie', 'F', '2009-12-30', NULL, NULL),
(66, 'Caroline', 'Emma', 'Shefcheck', NULL, NULL, 'F', '2013-04-18', NULL, NULL),
(67, 'Moddy', NULL, 'Frey', 'Suwatthi', NULL, 'F', '1980-10-07', NULL, 'Thailand'),
(68, 'Sharon', '', 'Wasnesky', NULL, NULL, 'F', '9999-05-13', NULL, NULL),
(69, 'William', 'Trey', 'Wasnesky', NULL, '', 'M', '2009-11-24', NULL, NULL),
(70, 'Anne', NULL, 'Kinkella', NULL, 'Toots', 'F', NULL, NULL, NULL),
(71, 'Lyra', 'Jade', 'Cartwright', NULL, 'Gal, LJ, Flabby, Flabbers, Lil Poops', 'F', '2017-09-02', NULL, 'Prob produced from our coitus around Thanksgiving'),
(72, 'Brenden', NULL, 'Boyle', NULL, 'Gordie', 'M', '9999-06-24', NULL, NULL),
(73, 'Delvin', 'James', 'Frey', NULL, NULL, 'M', '2017-03-23', NULL, 'Born at 1:38am on 3/23/2017\r\n6lbs 15oz and 19.25 inches long'),
(74, 'Frank', NULL, 'Ergan', NULL, NULL, 'M', '1916-05-10', '1994-04-23', NULL),
(75, 'Pauline', NULL, 'Ergan', 'Vozel', NULL, 'F', '1917-06-07', '1989-05-20', NULL),
(76, 'Nick', NULL, 'Naret', NULL, NULL, 'M', NULL, NULL, 'MSA'),
(77, 'Gary', 'Richard', 'Neal', NULL, NULL, 'M', '1979-04-19', NULL, NULL),
(78, 'Jeremy', NULL, 'Wein', NULL, NULL, 'M', '1981-09-13', NULL, 'Boston'),
(79, 'Zackary', 'Carlin', 'Wein', NULL, NULL, 'M', '2013-10-01', NULL, ''),
(80, 'Donovan', '', 'Wein', NULL, NULL, 'M', '2009-09-09', NULL, ''),
(81, 'Timothy', NULL, 'Krahn', NULL, 'Tim, The Royal King Krahn', 'M', NULL, NULL, 'MSA, came from financial dept at UPMC'),
(82, 'Martin', NULL, 'Mudoh', NULL, NULL, 'M', NULL, NULL, 'MSA, from Boston. Foreign guy.'),
(83, 'Adam', NULL, 'Evans', NULL, NULL, 'M', NULL, NULL, 'MSA, formerly Oleg Levin. '),
(84, 'Fred', NULL, 'Berg', NULL, 'Fredge', 'M', '9999-10-03', NULL, 'MSA'),
(85, 'Garrett', NULL, 'Lestochi', NULL, NULL, 'M', NULL, NULL, 'MSA'),
(86, 'Ryan', NULL, 'Stein', NULL, NULL, 'M', NULL, NULL, 'MSA'),
(87, 'Cindy', NULL, 'Atkin', 'Kinkela', '', 'F', '1957-01-22', NULL, NULL),
(88, 'Lana', NULL, 'Johnson', NULL, 'Lana J, Gibblets', 'F', '1975-01-30', NULL, NULL),
(89, 'Haley', NULL, 'Farro', NULL, NULL, 'F', '1992-08-15', NULL, 'Zip''s gf Feb 2017 to present'),
(90, 'Scott', NULL, 'Sanner', NULL, 'Scoot', 'M', NULL, NULL, 'Boy''s friend'),
(91, 'Fred', 'McFeely', 'Rogers', NULL, 'Mr Rogers', 'M', '1928-03-20', '2003-02-27', 'Mr Rogers Neighborhood'),
(92, 'Myron', 'Sidney', 'Cope', 'Kopelman', NULL, 'M', '1929-01-23', '2008-02-27', 'Yoi'),
(93, 'Leonard', 'Simon', 'Nimoy', NULL, 'Spock', 'M', '1931-03-26', '2015-02-27', NULL),
(94, 'Sean', NULL, 'Cardiff', NULL, '', 'M', '2007-02-08', NULL, 'Anne''s son'),
(95, 'Stella', 'Rose', 'Polk', NULL, NULL, 'F', '2015-02-06', NULL, 'Scott Polk''s daughter'),
(96, 'Hudson', 'Christopher', 'Fawcett', NULL, NULL, 'M', '2015-03-04', NULL, '9:20 am\r\n8lb 8oz\r\n20.5\r\nParents: Steve & Jessica'),
(97, 'Pierce', 'Flavian', 'Rindt', NULL, NULL, 'M', '2015-03-17', NULL, 'Kenny and Amber''s Son'),
(98, 'Thomas', 'Raymond', 'Ressler', 'Jr', 'TJ', 'M', '2011-03-24', NULL, 'Isaac''s half brother'),
(99, 'Haven', 'Kenneth', 'Rindt', NULL, NULL, 'M', '2011-03-31', NULL, 'Kenny and Amber''s Son'),
(100, 'Parker', 'Rose', 'Thomas', NULL, NULL, 'F', '2009-04-01', NULL, 'Dave Thomas daughter'),
(101, 'August', 'James', 'Luseberink', NULL, NULL, 'M', '2014-05-21', NULL, 'Dave son'),
(102, 'Chuck', 'Henry', 'Noll', NULL, NULL, 'M', '1932-01-02', '2014-06-13', 'Coach of the Steelers'),
(103, 'Thomas', 'Raymond', 'Ressler', 'Senior', '', 'M', '9999-12-31', '2012-06-21', 'Isaac Step dad #1'),
(104, 'Jocelyn', 'Noelle', 'Stein', NULL, NULL, 'F', '2014-07-13', NULL, 'Ryan Stein daughter'),
(105, 'Mason', 'Richard', 'Neal', NULL, NULL, 'M', '2014-07-16', NULL, 'Gary son'),
(106, 'Alexis', 'Morgan', 'Shaffer', NULL, NULL, 'F', '2014-07-28', NULL, 'Greg Shaffer daughter'),
(107, 'Mario', NULL, 'Lemiuex', NULL, 'Le Magnifique, Super Mario', 'M', '1965-10-05', NULL, NULL),
(108, 'Susan', 'Irene', 'Moser', NULL, NULL, 'F', '1947-03-24', '2018-02-22', 'Tim''s Mom'),
(109, 'Alfred', 'Matthew', 'Yankovic', NULL, 'Weird Al', 'M', '1959-10-23', NULL, NULL),
(110, 'Sideny', 'Patrick', 'Crosby', NULL, 'Sid the Kid', 'M', '1987-08-07', NULL, NULL),
(111, 'Jaromír', NULL, 'Jágr', NULL, 'Jags', 'M', '1972-02-15', NULL, NULL),
(112, 'Evgeni', 'Vladimirovich', 'Malkin', NULL, 'Geno', 'M', '1986-07-31', NULL, NULL),
(113, 'Marc-André', NULL, 'Fleury', NULL, 'Flower', 'M', '1984-11-28', NULL, NULL),
(114, 'Shirley', 'Ann', 'Manson', NULL, NULL, 'F', '1966-08-26', NULL, NULL),
(115, 'Kurt', 'Donald', 'Cobain', NULL, NULL, 'M', '1967-02-20', '1994-04-05', NULL),
(116, 'Brandi', NULL, 'Radocay', NULL, NULL, 'F', '1973-03-12', NULL, NULL),
(117, 'Stephen', 'William', 'Hawking', NULL, NULL, 'M', '1942-01-08', '2018-03-14', 'Theoretical Physicist '),
(118, 'Bernie', NULL, 'Sanders', NULL, NULL, 'M', '1941-09-08', NULL, 'Senator from Vermont'),
(119, 'Andrew', NULL, 'Schmitt', NULL, NULL, 'M', NULL, NULL, 'Boy''s friend from school'),
(120, 'John', NULL, 'Hufford', NULL, '', 'M', '9999-12-31', NULL, 'Nate & Melissa''s son'),
(121, 'Madison', 'Charlie', 'Hufford', NULL, '', 'F', '9999-12-31', NULL, 'John & Megan''s daughter'),
(122, 'Greg', NULL, 'Shaffer', NULL, NULL, 'M', '1974-11-03', NULL, 'Bought the land our house is on from this guy. '),
(123, 'Cari', 'L', 'Shaffer', NULL, NULL, 'F', '9999-12-06', NULL, 'Greg''s wife'),
(124, 'Ella', NULL, 'Cardiff', NULL, '', 'F', '2004-05-20', NULL, 'Anne''s daughter'),
(125, 'Pat', NULL, 'Altman', NULL, NULL, 'M', '1976-03-22', NULL, NULL),
(126, 'Suki', NULL, 'Intarasakda', NULL, NULL, 'F', '9999-12-31', NULL, 'Pat''s wife'),
(127, 'Adonis', NULL, 'Ciocca', NULL, NULL, 'M', '9999-12-31', NULL, 'Boy''s friend from school. '),
(128, 'Lily', NULL, 'Gilbert', NULL, NULL, 'F', '9999-12-31', NULL, 'Boy''s friend from school. Lives by Carnathans. '),
(129, 'Bekkah', 'Louise', 'Robinson', 'Ellis', 'Punkin', 'F', '1975-09-10', NULL, 'My high school gf. '),
(130, 'Martin', NULL, 'Kurtz IV', NULL, 'Marty', 'M', '1978-10-06', NULL, NULL),
(131, 'Frank', NULL, 'Danowski', NULL, NULL, 'M', '1975-11-03', NULL, 'Frank lived up at 40 Bushy Run Road. Bulldogs, always broke him bones'),
(132, 'James', NULL, 'Kudrna', NULL, NULL, 'M', '1981-11-01', NULL, 'Autumn''s post-Gaines bf from Chicago. '),
(133, 'Chuckie', NULL, 'Christner', NULL, 'Lil Chuckie', 'M', '9999-12-31', NULL, 'Chuck''s son. '),
(134, 'Rebecca', 'Lee', 'Josephic', 'Fresch', 'Becca', 'F', '1980-02-07', '2018-12-01', 'Nate''s sister, died from cancer.'),
(135, 'Gavin', 'Joesph', 'Stein', NULL, NULL, 'F', '2016-11-18', NULL, 'Ryan Stein son'),
(136, 'Timothy', NULL, 'McCabe', NULL, 'Tim', 'M', '1975-12-26', NULL, 'One of 3 founding members of the Congo''s.'),
(137, 'Lucia', 'Louise', 'Zupancic', NULL, NULL, 'F', '2018-12-26', NULL, '[1446]\r\n7lbs4oz\r\n21in'),
(138, 'Chenchen', NULL, 'He', NULL, NULL, 'F', '1989-03-21', NULL, 'MSA'),
(139, 'Heather', NULL, 'Bojarski', NULL, NULL, 'F', NULL, NULL, 'MSA'),
(140, 'Janice', NULL, 'Dutcher', NULL, 'Jan', 'F', NULL, NULL, 'MSA'),
(141, 'Dale', NULL, 'Mensch', NULL, NULL, 'M', NULL, NULL, 'MSA'),
(142, 'Mark', NULL, 'Shunk', NULL, NULL, 'M', NULL, NULL, 'Boy''s friend'),
(143, 'Kenneth', '', 'Rindt', NULL, 'Kenny', 'M', '1979-04-28', NULL, ''),
(144, 'Anubhav', '', 'Evatt', NULL, NULL, 'M', NULL, NULL, 'MSA'),
(145, 'Ernest', 'Martin', 'Nichols', '', 'Uncle Ern', 'M', '1957-04-15', '2019-10-23', NULL),
(146, 'Nate', NULL, 'Fresch', NULL, NULL, 'M', '1975-05-29', NULL, NULL),
(147, 'Andrew', NULL, 'MacGregor', NULL, NULL, 'M', '1975-10-30', NULL, NULL),
(148, 'Rachael', NULL, 'Buccicone', NULL, NULL, 'F', NULL, NULL, 'MSA'),
(149, 'Stan', NULL, 'Lee', NULL, 'Stanley Martin Lieber', 'M', '1922-12-28', '2018-11-12', 'Creator of MARVEL COMICS'),
(150, 'Genevieve', NULL, 'Grossman', NULL, NULL, 'F', NULL, NULL, 'Worked one week at MSA'),
(151, 'Matthew', NULL, 'Weyandt', NULL, '', 'M', '1980-11-14', NULL, NULL),
(152, 'Alice', 'Corinne', 'Zupancic', NULL, NULL, 'F', '2020-11-12', NULL, 'Born:\r\n12:18 am\r\n6lbs\r\n19 1/2 inches'),
(153, 'Brandon', NULL, 'Dezelan', NULL, NULL, 'M', '1976-11-15', NULL, NULL),
(154, 'Shigeru', NULL, 'Miyamoto', NULL, NULL, 'M', '1952-11-16', NULL, 'Greatest video game designer ever. Mario, Zelda, countless others'),
(155, 'Jerry', NULL, 'Hunt', NULL, NULL, 'M', NULL, NULL, 'MSA'),
(156, 'Savannah', NULL, 'Lehneke', NULL, NULL, 'F', '2002-12-17', NULL, 'Boy''s First real gf'),
(157, 'Cheryl', 'A', 'Neal', 'Palarino', NULL, 'F', '1955-05-13', '2022-01-22', 'Gary and Tom''s mom'),
(158, 'Edmund', NULL, 'Vecchio', NULL, 'Edzo', 'M', '1967-03-24', NULL, 'Met him at the pizza place when I lived on Sellers'),
(159, 'Gerard', NULL, 'Danosos', NULL, NULL, 'M', '1984-01-02', NULL, 'DGRC, Dermatologist '),
(161, 'Tim', NULL, 'Reza', NULL, 'Moth man', 'M', '1966-05-03', NULL, 'DGRC'),
(162, 'Patrick', 'David', 'Cartwright', NULL, NULL, 'M', '1956-05-06', NULL, 'Michael and Terry and Dee''s brother');

CREATE TABLE IF NOT EXISTS BEERJUVENATION (
  YEAR INTEGER PRIMARY KEY,
  YEAR_NAME TEXT,
  DESCRIPTION TEXT,
  MAIN_IMAGE_URL TEXT,
  SECONDARY_IMAGE_URLS TEXT[]
);

CREATE TABLE IF NOT EXISTS HOLIDAY_PHOTOS (
  YEAR INTEGER PRIMARY KEY,
  IMAGE_URL TEXT
);

CREATE TABLE IF NOT EXISTS CELEBRATIONS (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION TEXT,
  IS_DYNAMIC BOOLEAN DEFAULT FALSE,
  FIXED_MONTH INTEGER,
  FIXED_DAY INTEGER,
  RRULE_STRING VARCHAR(255),
  ICON VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS QUOTES (
  QUOTE_ID SERIAL PRIMARY KEY,
  QUOTE_AUTHOR VARCHAR(255),
  QUOTE_DESC TEXT NOT NULL
);
